### ISSUE TITLE
缺少datastream文件夹？

### ISSUE THREAD

**Issue by lillianfly** [xiaoshenxian/tfserver-core#1]
看着是缺少datastream文件夹下的代码

**Comment by xiaoshenxian** [comment]
那个在maven构建的时候会通过[datastream.proto](https://github.com/xiaoshenxian/tfserver-core/blob/master/src/main/proto/datastream.proto)自动生成，因而源码中没有。中央仓库的jar包是编译后的，也不会缺少。
